stages:
    - deploy

pages:
    stage: deploy
    image: busybox:latest
    script:
        - mkdir .public
        - cp -r ./* .public
        - rm -rf public
        - mv .public public
        - gzip -k -9 $(find public -type f)
        
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
            